### ISSUE TITLE
Error make.

### ISSUE THREAD

**Issue by killerwilmer** [segmentio/daydream#14]
building : lib/foreground/popup/index.js
/Volumes/Data/chrome/daydream/node_modules/duo/node_modules/step.js/index.js:87
      co(fn).apply(ctx, args.concat(next));
             ^
TypeError: Object #<Promise> has no method 'apply'
    at call (/Volumes/Data/chrome/daydream/node_modules/duo/node_modules/step.js/index.js:87:14)
    at null._onTimeout (/Volumes/Data/chrome/daydream/node_modules/duo/node_modules/step.js/index.js:68:5)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
make: *** [build] Error 8

**Comment by stevenmiller888** [comment]
@killerwilmer Are you running the latest version of Node?

**Comment by killerwilmer** [comment]
$ node --version
v0.10.13

**Comment by killerwilmer** [comment]
Thanks with a ( npm update -g ) works.

**Comment by stevenmiller888** [comment]
Awesome!
