### ISSUE TITLE
error : TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by mtaylorSF** [segmentio/daydream#33]
Ran into the following issue when running ```make```

Can you help out?

```➜  labs git clone https://github.com/segmentio/daydream.git && cd daydream && make
Cloning into 'daydream'...
remote: Counting objects: 663, done.
remote: Total 663 (delta 0), reused 0 (delta 0), pack-reused 663
Receiving objects: 100% (663/663), 3.74 MiB | 806.00 KiB/s, done.
Resolving deltas: 100% (336/336), done.
Checking connectivity... done.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
daydream@2.1.1 /Users/mtaylor/dev/labs/daydream
└─┬ duo@0.8.10
  ├── archy@0.0.2
  ├─┬ atomic-json@0.0.4
  │ └── enqueue@0.0.3
  ├── batch@0.5.3
  ├── bytes@1.0.0
  ├── co@3.1.0
  ├── co-exists@0.0.1
  ├─┬ co-fs@1.2.0
  │ ├─┬ co-from-stream@0.0.0
  │ │ └── co-read@0.0.1
  │ └── thunkify@0.0.1
  ├─┬ co-parallel@1.0.0
  │ └── co-thread@0.0.1
  ├─┬ commander@2.9.0
  │ └── graceful-readlink@1.0.1
  ├─┬ component-clone@0.2.3
  │ └── component-type@1.2.1
  ├── cp@0.1.1
  ├─┬ debug@2.3.3
  │ └── ms@0.7.2
  ├── delegates@0.0.3
  ├── duo-css-compat@0.0.4
  ├─┬ duo-main@0.0.3
  │ └─┬ mocha@1.21.5
  │   ├── commander@2.3.0
  │   ├─┬ debug@2.0.0
  │   │ └── ms@0.6.2
  │   ├── diff@1.0.8
  │   ├── escape-string-regexp@1.0.2
  │   ├─┬ glob@3.2.3
  │   │ ├── graceful-fs@2.0.3
  │   │ └── inherits@2.0.3
  │   ├── growl@1.8.1
  │   ├─┬ jade@0.26.3
  │   │ ├── commander@0.6.1
  │   │ └── mkdirp@0.3.0
  │   └── mkdirp@0.5.0
  ├─┬ duo-pack@1.0.10
  │ └─┬ combine-source-map@0.3.0
  │   ├── convert-source-map@0.3.5
  │   ├─┬ inline-source-map@0.3.1
  │   │ └── source-map@0.3.0
  │   └─┬ source-map@0.1.43
  │     └── amdefine@1.0.1
  ├─┬ duo-package@0.5.1
  │ ├─┬ enstore@0.0.2
  │ │ ├── monotonic-timestamp@0.0.8
  │ │ └── through@2.2.7
  │ ├─┬ gh-resolve@3.1.0
  │ │ └─┬ debug@1.0.4
  │ │   └── ms@0.6.2
  │ ├─┬ node-netrc@0.0.1
  │ │ └── netrc@0.1.4
  │ ├─┬ request@2.79.0
  │ │ ├── aws-sign2@0.6.0
  │ │ ├── aws4@1.5.0
  │ │ ├── caseless@0.11.0
  │ │ ├─┬ combined-stream@1.0.5
  │ │ │ └── delayed-stream@1.0.0
  │ │ ├── extend@3.0.0
  │ │ ├── forever-agent@0.6.1
  │ │ ├─┬ form-data@2.1.2
  │ │ │ └── asynckit@0.4.0
  │ │ ├─┬ har-validator@2.0.6
  │ │ │ ├─┬ chalk@1.1.3
  │ │ │ │ ├── ansi-styles@2.2.1
  │ │ │ │ ├─┬ has-ansi@2.0.0
  │ │ │ │ │ └── ansi-regex@2.0.0
  │ │ │ │ ├── strip-ansi@3.0.1
  │ │ │ │ └── supports-color@2.0.0
  │ │ │ ├─┬ is-my-json-valid@2.15.0
  │ │ │ │ ├── generate-function@2.0.0
  │ │ │ │ ├─┬ generate-object-property@1.2.0
  │ │ │ │ │ └── is-property@1.0.2
  │ │ │ │ └── jsonpointer@4.0.0
  │ │ │ └─┬ pinkie-promise@2.0.1
  │ │ │   └── pinkie@2.0.4
  │ │ ├─┬ hawk@3.1.3
  │ │ │ ├── boom@2.10.1
  │ │ │ ├── cryptiles@2.0.5
  │ │ │ ├── hoek@2.16.3
  │ │ │ └── sntp@1.0.9
  │ │ ├─┬ http-signature@1.1.1
  │ │ │ ├── assert-plus@0.2.0
  │ │ │ ├─┬ jsprim@1.3.1
  │ │ │ │ ├── extsprintf@1.0.2
  │ │ │ │ ├── json-schema@0.2.3
  │ │ │ │ └── verror@1.3.6
  │ │ │ └─┬ sshpk@1.10.1
  │ │ │   ├── asn1@0.2.3
  │ │ │   ├── assert-plus@1.0.0
  │ │ │   ├── bcrypt-pbkdf@1.0.0
  │ │ │   ├─┬ dashdash@1.14.1
  │ │ │   │ └── assert-plus@1.0.0
  │ │ │   ├── ecc-jsbn@0.1.1
  │ │ │   ├─┬ getpass@0.1.6
  │ │ │   │ └── assert-plus@1.0.0
  │ │ │   ├── jodid25519@1.0.2
  │ │ │   ├── jsbn@0.1.0
  │ │ │   └── tweetnacl@0.14.3
  │ │ ├── is-typedarray@1.0.0
  │ │ ├── isstream@0.1.2
  │ │ ├── json-stringify-safe@5.0.1
  │ │ ├─┬ mime-types@2.1.13
  │ │ │ └── mime-db@1.25.0
  │ │ ├── oauth-sign@0.8.2
  │ │ ├── qs@6.3.0
  │ │ ├── stringstream@0.0.5
  │ │ ├─┬ tough-cookie@2.3.2
  │ │ │ └── punycode@1.4.1
  │ │ ├── tunnel-agent@0.4.3
  │ │ └── uuid@3.0.0
  │ ├── semver@2.3.2
  │ ├─┬ tar-fs@0.4.1
  │ │ ├── mkdirp@0.3.5
  │ │ ├─┬ pump@0.3.5
  │ │ │ ├─┬ end-of-stream@1.0.0
  │ │ │ │ └─┬ once@1.3.3
  │ │ │ │   └── wrappy@1.0.2
  │ │ │ └── once@1.2.0
  │ │ └─┬ tar-stream@0.4.7
  │ │   ├─┬ bl@0.9.5
  │ │   │ └── readable-stream@1.0.34
  │ │   ├─┬ readable-stream@1.1.14
  │ │   │ ├── core-util-is@1.0.2
  │ │   │ ├── isarray@0.0.1
  │ │   │ └── string_decoder@0.10.31
  │ │   └── xtend@4.0.1
  │ └── thunkify@0.0.1
  ├── duo-parse@0.1.1
  ├─┬ duo-string-to-js@0.1.2
  │ └── string-to-js@0.0.1
  ├─┬ duo-test@0.4.1
  │ ├── bluebird@2.11.0
  │ ├── buffer-events@0.0.2
  │ ├── co-exec@1.1.0
  │ ├─┬ co-timeout@0.1.0
  │ │ └── ms@0.6.2
  │ ├─┬ debug@1.0.4
  │ │ └── ms@0.6.2
  │ ├── incasesensitive@1.0.0
  │ ├─┬ koa@0.8.2
  │ │ ├─┬ accepts@1.0.7
  │ │ │ ├── mime-types@1.0.2
  │ │ │ └── negotiator@0.4.7
  │ │ ├─┬ cookies@0.4.1
  │ │ │ └── keygrip@1.0.1
  │ │ ├── dethroy@1.0.2
  │ │ ├── error-inject@1.0.0
  │ │ ├── escape-html@1.0.3
  │ │ ├─┬ finished@1.2.2
  │ │ │ └── ee-first@1.0.3
  │ │ ├── fresh@0.2.4
  │ │ ├── koa-compose@2.3.0
  │ │ ├── koa-is-json@1.0.0
  │ │ ├── media-typer@0.2.0
  │ │ ├── mime-types@1.0.2
  │ │ ├── only@0.0.2
  │ │ ├── parseurl@1.2.0
  │ │ ├── statuses@1.0.4
  │ │ ├─┬ type-is@1.3.2
  │ │ │ └── mime-types@1.0.2
  │ │ └── vary@0.1.0
  │ ├─┬ koa-route@1.1.4
  │ │ ├── methods@0.1.0
  │ │ └── path-to-regexp@0.1.7
  │ ├─┬ koa-static@1.5.2
  │ │ └─┬ koa-send@2.0.2
  │ │   ├─┬ mz@2.6.0
  │ │   │ ├── any-promise@1.3.0
  │ │   │ ├── object-assign@4.1.0
  │ │   │ └─┬ thenify-all@1.6.0
  │ │   │   └── thenify@3.2.1
  │ │   └─┬ resolve-path@1.3.3
  │ │     ├─┬ http-errors@1.5.1
  │ │     │ ├── setprototypeof@1.0.2
  │ │     │ └── statuses@1.3.1
  │ │     └── path-is-absolute@1.0.1
  │ ├─┬ localtunnel@1.8.2
  │ │ ├─┬ debug@2.2.0
  │ │ │ └── ms@0.7.1
  │ │ ├── openurl@1.1.0
  │ │ ├─┬ request@2.78.0
  │ │ │ └── node-uuid@1.4.7
  │ │ └─┬ yargs@3.29.0
  │ │   ├── camelcase@1.2.1
  │ │   ├─┬ cliui@3.2.0
  │ │   │ ├─┬ string-width@1.0.2
  │ │   │ │ ├── code-point-at@1.1.0
  │ │   │ │ └─┬ is-fullwidth-code-point@1.0.0
  │ │   │ │   └── number-is-nan@1.0.1
  │ │   │ └── wrap-ansi@2.0.0
  │ │   ├── decamelize@1.2.0
  │ │   ├─┬ os-locale@1.4.0
  │ │   │ └─┬ lcid@1.0.0
  │ │   │   └── invert-kv@1.0.0
  │ │   ├── window-size@0.1.4
  │ │   └── y18n@3.2.1
  │ ├── open@0.0.5
  │ ├─┬ queue-component@1.0.6  (git://github.com/component/queue.git#23dbce0f19a714b020b4fc52ed07ac0365c9b449)
  │ │ ├── component-bind@1.0.0
  │ │ └── component-emitter@1.1.2
  │ ├─┬ to-pascal-case@0.0.2
  │ │ └─┬ to-space-case@0.1.2
  │ │   └── to-no-case@0.1.1
  │ ├─┬ wd@0.3.12
  │ │ ├─┬ archiver@0.14.4
  │ │ │ ├── async@0.9.2
  │ │ │ ├── buffer-crc32@0.2.13
  │ │ │ ├─┬ glob@4.3.5
  │ │ │ │ ├─┬ inflight@1.0.6
  │ │ │ │ │ └── once@1.4.0
  │ │ │ │ ├─┬ minimatch@2.0.10
  │ │ │ │ │ └─┬ brace-expansion@1.1.6
  │ │ │ │ │   ├── balanced-match@0.4.2
  │ │ │ │ │   └── concat-map@0.0.1
  │ │ │ │ └── once@1.4.0
  │ │ │ ├─┬ lazystream@0.1.0
  │ │ │ │ └── readable-stream@1.0.34
  │ │ │ ├── lodash@3.2.0
  │ │ │ ├── readable-stream@1.0.34
  │ │ │ ├── tar-stream@1.1.5
  │ │ │ └─┬ zip-stream@0.5.2
  │ │ │   ├─┬ compress-commons@0.2.9
  │ │ │   │ ├─┬ crc32-stream@0.3.4
  │ │ │   │ │ └── readable-stream@1.0.34
  │ │ │   │ ├── node-int64@0.3.3
  │ │ │   │ └── readable-stream@1.0.34
  │ │ │   ├── lodash@3.2.0
  │ │ │   └── readable-stream@1.0.34
  │ │ ├── async@1.0.0
  │ │ ├── lodash@3.9.3
  │ │ ├── q@1.4.1
  │ │ ├─┬ request@2.55.0
  │ │ │ ├── aws-sign2@0.5.0
  │ │ │ ├── caseless@0.9.0
  │ │ │ ├─┬ combined-stream@0.0.7
  │ │ │ │ └── delayed-stream@0.0.5
  │ │ │ ├─┬ form-data@0.2.0
  │ │ │ │ └── async@0.9.2
  │ │ │ ├── har-validator@1.8.0
  │ │ │ ├── hawk@2.3.1
  │ │ │ ├─┬ http-signature@0.10.1
  │ │ │ │ ├── asn1@0.1.11
  │ │ │ │ ├── assert-plus@0.1.5
  │ │ │ │ └── ctype@0.5.3
  │ │ │ ├─┬ mime-types@2.0.14
  │ │ │ │ └── mime-db@1.12.0
  │ │ │ ├── node-uuid@1.4.7
  │ │ │ ├── oauth-sign@0.6.0
  │ │ │ └── qs@2.4.2
  │ │ ├── underscore.string@3.0.3
  │ │ └── vargs@0.1.0
  │ ├── wd-browser@1.1.0
  │ └─┬ which@1.2.12
  │   └── isexe@1.1.2
  ├─┬ duo-watch@0.1.1
  │ ├─┬ debug@1.0.4
  │ │ └── ms@0.6.2
  │ ├─┬ minimatch@1.0.0
  │ │ ├── lru-cache@2.7.3
  │ │ └── sigmund@1.0.1
  │ └─┬ sane@0.5.4
  │   ├── minimatch@0.2.14
  │   ├─┬ walker@1.0.7
  │   │ └─┬ makeerror@1.0.11
  │   │   └── tmpl@1.0.4
  │   └── watch@0.10.0
  ├── extend.js@0.0.1
  ├─┬ file-deps@0.0.7
  │ ├─┬ detective@3.1.0
  │ │ ├─┬ escodegen@1.1.0
  │ │ │ ├── esprima@1.0.4
  │ │ │ ├── estraverse@1.5.1
  │ │ │ └── esutils@1.0.0
  │ │ └── esprima-fb@3001.1.0-dev-harmony-fb
  │ ├── escape-regexp@0.0.1
  │ └── mini-tokenizer@0.1.2
  ├── get-stdin@1.0.0
  ├─┬ gnode@0.1.0
  │ └─┬ regenerator@0.6.10
  │   ├── commander@2.3.0
  │   ├─┬ defs@1.0.1
  │   │ ├─┬ alter@0.2.0
  │   │ │ └── stable@0.1.5
  │   │ ├── ast-traverse@0.1.1
  │   │ ├── breakable@1.0.0
  │   │ ├── esprima@1.1.0-dev-harmony  (git://github.com/ariya/esprima.git#a65a3eb93b9a5dce9a1184ca2d1bd0b184c6b8fd)
  │   │ ├── simple-fmt@0.1.0
  │   │ ├── simple-is@0.2.0
  │   │ ├── stringmap@0.2.2
  │   │ ├── stringset@0.2.1
  │   │ ├── tryor@0.1.2
  │   │ └── yargs@1.3.3
  │   ├── esprima-fb@7001.1.0-dev-harmony-fb
  │   ├── private@0.1.6
  │   ├─┬ promise@6.0.1
  │   │ └── asap@1.0.0
  │   ├─┬ recast@0.9.18
  │   │ ├── ast-types@0.6.16
  │   │ └── esprima-fb@10001.1.0-dev-harmony-fb
  │   └── through@2.3.8
  ├── json-mask@0.3.8
  ├─┬ language-classifier@0.0.1
  │ └─┬ classifier@0.1.0
  │   ├─┬ redis@2.6.3
  │   │ ├── double-ended-queue@2.1.0-0
  │   │ ├── redis-commands@1.3.0
  │   │ └── redis-parser@2.2.0
  │   └── underscore@1.8.3
  ├─┬ max-component@1.0.0
  │ └─┬ to-function@2.0.6
  │   └── component-props@1.1.1
  ├─┬ mkdirp@0.5.1
  │ └── minimist@0.0.8
  ├── step.js@2.0.5
  ├── stream-log@0.1.0
  ├── thunkify@2.1.2
  ├── unyield@0.0.1
  └── win-fork@1.1.1

npm WARN daydream@2.1.1 No license field.

     building : lib/foreground/popup/index.js
    installed : segmentio-highlight-javascript@0.0.3
    installed : segmentio-highlight@0.0.3
    installed : component-emitter@1.2.1
        error : TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at extname (path.js:1433:5)
    at extension (/Users/mtaylor/dev/labs/daydream/node_modules/duo-main/index.js:135:10)
    at dependency (/Users/mtaylor/dev/labs/daydream/node_modules/duo-main/index.js:83:16)
    at coerce (/Users/mtaylor/dev/labs/daydream/node_modules/duo-main/index.js:31:7)
    at Duo.resolve (/Users/mtaylor/dev/labs/daydream/node_modules/duo/lib/duo.js:716:22)
    at next (native)
    at next (/Users/mtaylor/dev/labs/daydream/node_modules/co/index.js:74:21)
    at Duo.<anonymous> (/Users/mtaylor/dev/labs/daydream/node_modules/co/index.js:45:5)
    at Duo.next (/Users/mtaylor/dev/labs/daydream/node_modules/co/index.js:90:21)

make: *** [build] Error 1

➜  daydream git:(master) make
make: Nothing to be done for `default'.```

**Comment by stevenmiller888** [comment]
@mtaylorSF I've refactored the build process and don't expect you to run into this issue again.
